[phases.setup]
nixPkgs = { nodejs = "18", php = "82" }

[phases.install]
cmds = [
    "composer install --no-dev --optimize-autoloader",
    "npm ci",
    "chmod +x start.sh"
]

[phases.build]
cmds = [
    "npx vite build",
    "php artisan config:cache",
    "php artisan route:cache",
    "php artisan view:cache"
]

[start]
cmd = "./start.sh"

